version: '3'
services:
    php-apache:
        build: 
            context: ./docker/php-apache
        ports:
            - 80:80
        volumes:
            - ./www:/var/www/html
        links:
            - 'mariadb'

    mariadb:
      image: mariadb:10.1
      volumes:
        - ./docker/mariadb:/var/lib/mysql
      ports:
        - 3306:3306
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "no"
        MYSQL_ROOT_PASSWORD: "rootpwd"
        MYSQL_USER: 'testuser'
        MYSQL_PASSWORD: 'testpassword'
        MYSQL_DATABASE: 'testdb'
